version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: rails_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rails_mysql_development
    ports:
      - "3307:3306"
    networks:
      - trandung
  backend:
    container_name: rails_mysql
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # command: rails db:migrate
    command: bundle exec rails server -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: rails_mysql_development
      DB_PASSWORD: admin
      DB_HOST: db
    networks:
      - trandung
volumes:
  mysql:
networks:
  trandung: